export const GET_TOP_TRACKS_FAILED = 'GET_TOP_TRACKS_FAILED';
export const GET_ARTIST_INFO_FAILED = 'GET_ARTIST_INFO_FAILED';
export const GET_SEARCH_TRACKS_FAILED = 'GET_SEARCH_TRACKS_FAILED';
export const SEARCH_TRACKS_STATUS = 'SEARCH_TRACKS_STATUS';
export const GET_TOP_TRACKS = 'GET_TOP_TRACKS';
export const GET_ARTIST_INFO = 'GET_ARTIST_INFO';
export const GET_SEARCH_TRACKS = 'GET_SEARCH_TRACKS';
